[project]
name = "search-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opensearch-py>=2.8.0",
    "requests>=2.32.3",
    "tika>=3.1.0",
]
